### ISSUE TITLE
update to use Prisma-Client

### ISSUE THREAD

**Issue by victory1908** [frandiox/vue-graphql-enterprise-boilerplate#36]
Hi with the release of `Prisma-Client`. Should the project be updated to use `Prisma-Client?`

**Comment by frandiox** [comment]
@victory1908 Hi, thanks for commenting.

Prisma client does not really replace Prisma bindings. They overlap for most of the features but bindings are a super set of client. In fact, I find bindings to be more useful for my apps due to the schema delegation feature. Some people use a hybrid approach and use both tools. To be honest, I haven't faced any situation where client can do something that bindings cannot so I don't really see the point in adding client.

Therefore, at least for now, I prefer to continue using bindings even if it's not the "default" tool for Prisma anymore (it's official and more mature than client).
