### ISSUE TITLE
Server as mock-api

### ISSUE THREAD

**Issue by marceloavf** [frandiox/vue-graphql-enterprise-boilerplate#40]
## Question

The server can be ignored or used as a mock-api as chris does in his boilerplate, since my team will work in another stack for the backend?

I really liked your way of integrating graphql inside of it, but I was just looking for something with just GraphQL integrated with it.

Thank you @frandiox!

**Comment by frandiox** [comment]
@marceloavf Hey! I think it's fairly easy to change the server, it should be completely independent from the client. The only thing that needs to be consistent is that `VUE_APP_GRAPHQL_HTTP="http://localhost:4000/graphql"` endpoint needs to understand GraphQL by using Apollo Server or something similar. Also, if you want to keep Auth0 for authentication, then you need to implement a similar `authenticate` mutation in your new stack.

Let me know if this answers your question 👍

**Comment by marceloavf** [comment]
That's exactly what I needed @frandiox!

Our back end team will use apollo server and as they say no Auth0, so I just need to convert this server into a strictly mock api for the tests.

Thank you again! 😃

**Comment by frandiox** [comment]
@marceloavf Hi!

### Removing Prisma

Delete the following folders: `server/database`, `server/__mocks__` and `server/src/generated`. Also, clear all references in `server/package.json`. If you want to keep the current user-post example, in `server/schema/index.graphql`, you need to implement all the types that were previously imported from Prisma (Post and Role). Finally, modify `server/db.js` and `server/models/` to use your new database/ source of data.

### Removing Auth0

It really depends on your new authentication system. If it's based on JWT, you can keep most of the things but adapt them to your new JWT issuer. The files you need to modify for this are `server/src/middleware/verify-access-token.js`, `server/src/middleware/get-user-auth.js` and `server/src/resolvers/mutation/auth.js`. 

The first file is verifying the JWT in the headers so you need to update the issuer information and all of that.

The second one is getting a user from DB based on the access token information. Ideally, your access token will contain enough information to perform authorization (id and role) to skip DB requests. If it doesn't, then it should get the necessary information from DB.

The third file checks the idToken to log in or create a new user if it doesn't exists. This will depend a lot on your new authentication method. If you send email/password instead of idTokens then you'd need to modify all of this and possibly return your own accessToken. Note that SSN auth providers like Google or Facebook (OAuth 2.0) may still give you an idToken.

After that, all you need to do is changing `src/services/auth/` accordingly and call your new authentication backend instead of calling Auth0 API. I.e. call your own "reset password", "login", "signup", etc. endpoints.

### Faking responses

I think the best way would be including graphql-faker. I wanted to do this earlier but didn't find time for it, so I can't help much yet.


Feel free to ask if something is not clear 👍

**Comment by marceloavf** [comment]
Thank you so much for the detailed response @frandiox !

I'll be forking this repo, doing the changes and try to keep it intact as a boilerplate without Auth0 and Prisma, if it's not a problem for you.

I'm deeply searching **graphql-faker** and I had a question, since it runs an entirely server by just writing GraphQL IDL, it will be no need to keep this entire server of yours, am I right?

Thank you again! 😄

**Comment by frandiox** [comment]
@marceloavf If you want we can add a branch without Prisma/Auth0 because it's easier to focus efforts in one repo. I can add you as a collaborator if you are interested :)

**Comment by marceloavf** [comment]
Would be nice @frandiox!

I'm trying to remove Auth0 first, keeping JWT because it is commonly used and we also use it.

**Comment by frandiox** [comment]
I just added you as a collaborator, you can create a new branch with the modifications.

About graphql-faker, it is just for testing, not for production. If that's all what you want then there is no need for a server. However, the boilerplate is meant to be used in production without faked requests so it needs the server.

**Comment by marceloavf** [comment]
Nice, get it!

Prisma can run locally without the need of endpoints and secret token? If so, I could leave it to speed up development and create some docker config for the database.

I believe that the tasks to be performed are these one below.

- [ ] Remove Auth0 implementation.
- [ ] Remove Prisma implementation?.
- [ ] Include Graphql-faker to run with tests using predefined GraphQL IDL if possible.

**Comment by frandiox** [comment]
I think that's correct.

About Prisma, it can run locally by using docker-compose with Prisma itself and a local DB: https://www.prisma.io/docs/prisma-server/local-prisma-setup-je3i/
However, I think the fastest way to get started is using their demo servers (Prisma + DB for free but requires internet connection), which is what this boilerplate is currently using: https://www.prisma.io/docs/prisma-server/demo-servers-prisma-cloud-jfr3/

I'm not sure if you need `fetch-graphql-schema` since you already have `server/src/schema/...` files 🤔

**Comment by marceloavf** [comment]
Excellent, so I'll keep this the way it is for this boilerplate.

I think `fetch-graphql-schema` will be useful for me, because I do have another team working in a separately server, so I can copy their schema or some third party for local test.

I'll begin removing Auth0 (from what I saw, it's going to be my only impediment) and trying to implement graphql-faker for tests.

**Comment by marceloavf** [comment]
The `.graphqlconfig.yml` is necessary when you don't have a server @frandiox ?
Because I'm receiving a lot of errors in vs code console like this:

```
[Error - 1:09:55 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'projectName' of undefined
  Code: -32603 
(node:9420) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 173): TypeError: Cannot read property 'schemaPath' of undefined
```

Thank you!

**Comment by frandiox** [comment]
@marceloavf `.graphqlconfig.yml` was used by some VSCode plugin to autocomplete gql queries from the frontend. You can remove it if you want.

I've no idea about Apollo devtools. I've seen some inconsistencies with it in the past but I assumed it was a bug in the plugin and didn't pay much attention 🤔
